# Generated by Django 6.0.3 on 2026-04-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
